# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/huanglf/workspace/proj_debug/debug/cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/huanglf/workspace/proj_debug/debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huanglf/workspace/proj_debug/debug/CMakeFiles /home/huanglf/workspace/proj_debug/debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huanglf/workspace/proj_debug/debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named lib

# Build rule for target.
lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib
.PHONY : lib

# fast build rule for target.
lib/fast:
	$(MAKE) -f CMakeFiles/lib.dir/build.make CMakeFiles/lib.dir/build
.PHONY : lib/fast

src/debug_bio.o: src/debug_bio.c.o

.PHONY : src/debug_bio.o

# target to build an object file
src/debug_bio.c.o:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_bio.c.o
.PHONY : src/debug_bio.c.o

src/debug_bio.i: src/debug_bio.c.i

.PHONY : src/debug_bio.i

# target to preprocess a source file
src/debug_bio.c.i:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_bio.c.i
.PHONY : src/debug_bio.c.i

src/debug_bio.s: src/debug_bio.c.s

.PHONY : src/debug_bio.s

# target to generate assembly for a file
src/debug_bio.c.s:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_bio.c.s
.PHONY : src/debug_bio.c.s

src/debug_dump.o: src/debug_dump.c.o

.PHONY : src/debug_dump.o

# target to build an object file
src/debug_dump.c.o:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_dump.c.o
.PHONY : src/debug_dump.c.o

src/debug_dump.i: src/debug_dump.c.i

.PHONY : src/debug_dump.i

# target to preprocess a source file
src/debug_dump.c.i:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_dump.c.i
.PHONY : src/debug_dump.c.i

src/debug_dump.s: src/debug_dump.c.s

.PHONY : src/debug_dump.s

# target to generate assembly for a file
src/debug_dump.c.s:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_dump.c.s
.PHONY : src/debug_dump.c.s

src/debug_in.o: src/debug_in.c.o

.PHONY : src/debug_in.o

# target to build an object file
src/debug_in.c.o:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_in.c.o
.PHONY : src/debug_in.c.o

src/debug_in.i: src/debug_in.c.i

.PHONY : src/debug_in.i

# target to preprocess a source file
src/debug_in.c.i:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_in.c.i
.PHONY : src/debug_in.c.i

src/debug_in.s: src/debug_in.c.s

.PHONY : src/debug_in.s

# target to generate assembly for a file
src/debug_in.c.s:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_in.c.s
.PHONY : src/debug_in.c.s

src/debug_log.o: src/debug_log.c.o

.PHONY : src/debug_log.o

# target to build an object file
src/debug_log.c.o:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_log.c.o
.PHONY : src/debug_log.c.o

src/debug_log.i: src/debug_log.c.i

.PHONY : src/debug_log.i

# target to preprocess a source file
src/debug_log.c.i:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_log.c.i
.PHONY : src/debug_log.c.i

src/debug_log.s: src/debug_log.c.s

.PHONY : src/debug_log.s

# target to generate assembly for a file
src/debug_log.c.s:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_log.c.s
.PHONY : src/debug_log.c.s

src/debug_out.o: src/debug_out.c.o

.PHONY : src/debug_out.o

# target to build an object file
src/debug_out.c.o:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_out.c.o
.PHONY : src/debug_out.c.o

src/debug_out.i: src/debug_out.c.i

.PHONY : src/debug_out.i

# target to preprocess a source file
src/debug_out.c.i:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_out.c.i
.PHONY : src/debug_out.c.i

src/debug_out.s: src/debug_out.c.s

.PHONY : src/debug_out.s

# target to generate assembly for a file
src/debug_out.c.s:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_out.c.s
.PHONY : src/debug_out.c.s

src/debug_test.o: src/debug_test.c.o

.PHONY : src/debug_test.o

# target to build an object file
src/debug_test.c.o:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_test.c.o
.PHONY : src/debug_test.c.o

src/debug_test.i: src/debug_test.c.i

.PHONY : src/debug_test.i

# target to preprocess a source file
src/debug_test.c.i:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_test.c.i
.PHONY : src/debug_test.c.i

src/debug_test.s: src/debug_test.c.s

.PHONY : src/debug_test.s

# target to generate assembly for a file
src/debug_test.c.s:
	$(MAKE) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/src/debug_test.c.s
.PHONY : src/debug_test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lib"
	@echo "... debug"
	@echo "... src/debug_bio.o"
	@echo "... src/debug_bio.i"
	@echo "... src/debug_bio.s"
	@echo "... src/debug_dump.o"
	@echo "... src/debug_dump.i"
	@echo "... src/debug_dump.s"
	@echo "... src/debug_in.o"
	@echo "... src/debug_in.i"
	@echo "... src/debug_in.s"
	@echo "... src/debug_log.o"
	@echo "... src/debug_log.i"
	@echo "... src/debug_log.s"
	@echo "... src/debug_out.o"
	@echo "... src/debug_out.i"
	@echo "... src/debug_out.s"
	@echo "... src/debug_test.o"
	@echo "... src/debug_test.i"
	@echo "... src/debug_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

